### PR TITLE
Update DataTables Dependencies for new DataTables Version

### PR DESCRIPTION
**Pull request by herpaderpaldent**
This resolves: https://github.com/eveseat/seat/issues/418

### CODE REVIEW

**Comment by warlof** [comment]
this one is all good for me

**Comment by warlof** [comment]
I suggest to report this to the end of DataTable server side integration as operations made for this project will need update on this pull request.

**Comment by warlof** [comment]
I'm not against the datatable upgrade, neither the move to the server side. 

It's just two distinct project which can lead to merge conflict or unwanted issues. Actually all pending pull requests are based on the current version.

**Comment by herpaderpaldent** [comment]
let's just agree on how to proceed? I would propose the following order:

1. merge the approved Assets-View: https://github.com/eveseat/web/pull/209 
2. Adapt DataTable Dependencies for Assets and Merge
3. Adapt all oter DataTable ServerSide improvements (as there are change requests and feedbacks to incooperate). 

What do you think?

**Comment by warlof** [comment]
well, since you already move a few other table to server side, I rather think
 1. move all table to server side
 2. bump datatable factory to 8.x
 3. introduce feedback into tables

**Pull request merged**
