### PR TITLE
Provide native support for Discord notifications

### PR DESCRIPTION
**Pull request by warlof**

### CODE REVIEW

**Comment by maxtsero** [comment]
Can we do anything to help test this?

**Comment by warlof** [comment]
It needs to be completed, but you should be able to use all concerted format yet.

**Comment by maxtsero** [comment]
Great, we'll see about testing this out as Discord notifications are a huge plus for us :-)

**Comment by grimreap124** [comment]
I was wondering if there was anything I could of to help get this released.

**Comment by warlof** [comment]
@grimreap124 resting and add missing notification. All existing haven't be switched to discord formatter

**Comment by recursivetree** [comment]
What is the state on this? Can we get it into seat 5? If it's just completing a few notification, I can do it.

**Comment by warlof** [comment]
Mostly, I think - and maybe a few tests
I can rebase the branch

**Comment by recursivetree** [comment]
I suggest once it's working we merge this without all notifications. They can be added later, and it's easier to PR into the main repo that into another PR.

**Pull request closed without merging**
